### ISSUE TITLE
Firmware uf2 file link dead because removed from repo.

### ISSUE THREAD

**Issue by francisduvivier** [sqfmi/beepy-docs#10]
Making this issue for awareness.

In this commit:
https://github.com/sqfmi/i2c_puppet/commit/ffe7329d789dabf82384669181f572176a6bae63
the i2c_puppet.uf2 file was removed from the tip of the main branch file tree. 
So the link on the docs is not working anymore.

Solution for us users is to either:
- build the firmware ourselves
- get the old firmware from that commit
- use the prebuilt binary from this fork: https://github.com/wildoracle/beepy/blob/main/i2c_puppet.uf2

**Comment by sqfmi** [comment]
Thanks! The link should now be fixed. The binary is now available with the tagged releases: https://github.com/sqfmi/i2c_puppet/releases/latest/download/i2c_puppet.uf2
