### ISSUE TITLE
Step 4 of the getting started guide contains a broken link

### ISSUE THREAD

**Issue by Retrograde-i486** [sqfmi/beepy-docs#19]
Step 4 of the getting started guide says to review the default symbol keymap but this leads to a 404:

https://github.com/sqfmi/beepy-docs/blob/main/docs/keyboard

Your Beepy is now ready, enjoy!
        Review the [default symbol keymap](https://github.com/sqfmi/beepy-docs/blob/main/docs/keyboard)
![404](https://github.com/sqfmi/beepy-docs/assets/65242258/6d281ece-54e7-4212-86fc-51ce81eb1611)

**Comment by sqfmi** [comment]
Resolved, thanks!
